### ISSUE TITLE
Add column of input data type

### ISSUE THREAD

**Issue by Jack-Lin-DS-AI** [EliotAndres/kaggle-past-solutions#16]
Current "Type" column is the problem type. I think it would be beneficial to add the input data type as well. For example, tubular, text, image, voice, and mixture of more than one ...
What do you think?

**Comment by EliotAndres** [comment]
Thank you for this idea. Currently, using the search box you can find `image` competitions (it'll search in `title` and `type`). Most of the other competitions are using structured data.

Moreover, I think there are too many columns already, some of them almost empty. If you want to add the data type, we could add it under the current type (in the same column).

Feel free to make a pull request 😄
