### ISSUE TITLE
Stopped updating?

### ISSUE THREAD

**Issue by ubershmekel** [EliotAndres/kaggle-past-solutions#19]
Seems the most recent competition at https://ndres.me/kaggle-past-solutions/ has the deadline of 2018-08-30.

Is the site temporarily broken or deprecated?

**Comment by EliotAndres** [comment]
Hey ! Thank you for raising this issue. I no longer have the time to update the website. Instructions for updating are in the readme though, feel free to submit a pull request :-) 

I'm keeping this issue open to let people know that the website is no longer up to date.

**Comment by ubershmekel** [comment]
Oh, this was completely manually curated? Interesting.

**Comment by EliotAndres** [comment]
I updated the page with the latest links, closing this.
