### ISSUE TITLE
Add column for source code/github link

### ISSUE THREAD

**Issue by Shujian2015** [EliotAndres/kaggle-past-solutions#3]
Hi, thanks for this wonderful website. I am considering to contribute to this repo and very interested in adding winning source code/Github link. Is it possible/easy to add one column for that? Thanks.

PS: I have collected some Github links here: http://shujianliu.com/kaggle-winning-code.html

**Comment by EliotAndres** [comment]
Hi ! I just saw the PR. Adding the repos would be great. Do you want me to add a column ?

**Comment by Shujian2015** [comment]
Hi, Eliot, if you have time to add a column, that would be great!

**Comment by EliotAndres** [comment]
I added a new field, `repositories`, in competitions.json. You can see an example [here](https://github.com/EliotAndres/kaggle-past-solutions/commit/9353d456c9a6ee91377ec9a793a45f4f124b1ffa)

Feel free to complete it 😄

**Comment by Shujian2015** [comment]
Great! Thanks. I will do some modification today or tomorrow.
