### ISSUE TITLE
Also: blog post by winners

### ISSUE THREAD

**Issue by stared** [EliotAndres/kaggle-past-solutions#8]
How about including blog post by winners?
Some of them are really insightful!

* [Which whale is it, anyway? Face recognition for right whales using deep learning](https://deepsense.io/deep-learning-right-whale-recognition-kaggle/) (1st place, deepsense.io team)
* [Deep learning for satellite imagery via image segmentation](https://deepsense.io/deep-learning-for-satellite-imagery-via-image-segmentation/) (4th place, deepsense.io team)
* [Predicting lung cancer](https://eliasvansteenkiste.github.io/machine%20learning/lung-cancer-pred/) (9th place, Deep Breath team)
* etc...

Especially rather than splitting into `interviews` and `repositories` categories, grouping by places, and then allowing entries of various kinds.

**Comment by EliotAndres** [comment]
That's a great idea ! I feel like it would fit into interviews (isn't a blog post a self interview 😀 ?).

I just renamed `Interviews` to `Interviews and articles` in the html. Feel free to add the blog posts under the `interviews` key in the json file.

**Comment by stared** [comment]
Great!

Off-topic:

*  is this framework yours and can be copy-pasted for other collaborative lists? (Recently I shared [this one](https://github.com/stared/science-based-games-list), but it is now markdown-based.)
* for human-editable files, why not YAML? :)

**Comment by EliotAndres** [comment]
You are free to re-use the framework ! (I'll add a LICENSE file this evening). I usually prefer markdown based lists but here I felt full-text search could be useful.

Using JSON allowed me to just pull the competitions from Kaggle and add the missing categories 😄
